### ISSUE TITLE
SIS

### ISSUE THREAD

**Issue by naarkhoo** [wwrechard/screening#1]
I am kind of surprised by the SIS implementation

```
 else if (method == "sis") {
                OLS = t(X) %*% Y
```

I was always thinking, it is a series of uni variate model (correlation / regression) - but It seems the in the implementation, you are sorting OLS coefficients. I appreciate to hear your comments,

**Comment by wwrechard** [comment]
Although the variable name `OLS` is used in the code, it does not mean the implementation used OLS coefficient -- I just want to keep the variable name consistent for all screening methods. If you look at how `OLS` is computed for `method == "sis"`, you will realize this is the marginal correlation, as suggested in Fan and Lv (2008). Once the columns of `X` are standardized, doing

```
OLS = t(X) %*% Y
```

is equivalent to 

```
for (i in 1 : dim(X)[2]) {
    OLS[i] = t(X[, i]) %*% Y / (t(X[, i]) %*% X[, i])
}
```

where the latter is exactly how you compute marginal correlation. The first code is much more efficient in R.
<br>
It is easier to clarify the difference between the usual OLS and marginal correlation by looking at their formula. The code for the usual OLS should be

```
OLS = solve(t(X) %*% X) %*% (t(X) %*% Y)
```

or more efficiently,

```
OLS = solve(t(X) %*% X, t(X) %*% Y)
```

as opposite to what was implemented in this package for `"sis"`

```
OLS = t(X) %*% Y
```

Hope this answered your question!
